trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: ProductionVariables
  - name: clientAppPath
    value: 'AspNetReactTemplate.Client'
  - name: serverProjectPath
    value: 'AspNetReactTemplate.Server/AspNetReactTemplate.Server.csproj'


steps:
  - task: UseNode@1
    inputs:
      version: '20.x'
    displayName: 'Install Node.js'

  - script: |
      cd $(clientAppPath)
      npm install
      npm run build
    displayName: 'NPM Install and Build (Vite)'


  - task: UseDotNet@2
    displayName: Use Dotnet 10
    inputs:
      version: "10.x" 

  - script: dotnet clean $(serverProjectPath)
    displayName: 'dotnet clean'

  - script: dotnet build $(serverProjectPath)
    displayName: "dotnet build"

  - script: dotnet publish $(serverProjectPath) -o publish
    displayName: "dotnet publish"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    inputs:
      PathtoPublish: "publish"
      ArtifactName: "application"